"""存储层协议定义"""

from typing import Protocol, Optional, List, Dict, Any

from .models import (
    Task,
    SessionNote,
    RemoteHostConfig,
    Requirement,
    RequirementSessionLink,
    ArchivedSession,
)


class StorageProtocol(Protocol):
    """存储层协议"""

    # Tasks
    def load_tasks(self) -> List[Task]: ...
    def save_tasks(self, tasks: List[Task]) -> None: ...

    # Notes
    def load_notes(self) -> Dict[str, SessionNote]: ...
    def save_notes(self, notes: Dict[str, SessionNote]) -> None: ...

    # Bookmarks
    def load_bookmarks(self) -> List[str]: ...
    def save_bookmarks(self, bookmarks: List[str]) -> None: ...

    # Config
    def load_config(self) -> Dict[str, Any]: ...
    def save_config(self, config: Dict[str, Any]) -> None: ...

    # Remote Hosts
    def load_remote_hosts(self) -> List[RemoteHostConfig]: ...
    def save_remote_hosts(self, hosts: List[RemoteHostConfig]) -> None: ...
    def add_remote_host(self, host: RemoteHostConfig) -> None: ...
    def remove_remote_host(self, host_id: str) -> bool: ...
    def get_remote_host(self, host_id: str) -> Optional[RemoteHostConfig]: ...

    # Requirements
    def load_requirements(self) -> List[Requirement]: ...
    def save_requirements(self, requirements: List[Requirement]) -> None: ...
    def add_requirement(self, requirement: Requirement) -> None: ...
    def get_requirement(self, req_id: str) -> Optional[Requirement]: ...
    def update_requirement(self, req_id: str, **kwargs) -> bool: ...
    def remove_requirement(self, req_id: str) -> bool: ...

    # Requirement Session Links
    def load_requirement_links(self) -> List[RequirementSessionLink]: ...
    def save_requirement_links(self, links: List[RequirementSessionLink]) -> None: ...
    def link_session_to_requirement(self, link: RequirementSessionLink) -> None: ...
    def unlink_session(self, session_id: str) -> bool: ...
    def get_session_requirement(self, session_id: str) -> Optional[RequirementSessionLink]: ...
    def get_requirement_sessions(self, req_id: str) -> List[RequirementSessionLink]: ...

    # Archived Sessions
    def load_archived_sessions(self) -> List[ArchivedSession]: ...
    def save_archived_sessions(self, sessions: List[ArchivedSession]) -> None: ...
    def archive_session(self, session_id: str, archive_type: str = "archived", **kwargs) -> ArchivedSession: ...
    def restore_session(self, session_id: str) -> bool: ...
    def get_archived_session(self, session_id: str) -> Optional[ArchivedSession]: ...
    def get_archived_by_type(self, archive_type: str) -> List[ArchivedSession]: ...
    def delete_trash_session(self, session_id: str) -> bool: ...

    # Stats Cache
    def load_stats_cache(self) -> Dict[str, Dict[str, Any]]: ...
    def save_stats_cache(self, cache: Dict[str, Dict[str, Any]]) -> None: ...
    def get_cached_stats(self, session_id: str) -> Optional[Dict[str, Any]]: ...
    def update_stats_cache(self, session_id: str, stats: Dict[str, Any]) -> None: ...

    # Remote Sessions Cache
    def get_cached_remote_sessions(self, host_id: str) -> Optional[List[Dict[str, Any]]]: ...
    def save_cached_remote_sessions(self, host_id: str, sessions: List[Dict[str, Any]]) -> None: ...
    def clear_remote_sessions_cache(self, host_id: str) -> None: ...
